### ISSUE TITLE
Add pre-commit linking using markdownlint-cli2

### ISSUE THREAD

**Issue by ns-rse** [r-devel/r-dev-env#194]
Further to #191 it might be useful to implement a [pre-commit](https://pre-commit.com) hook for [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) and combine it with a [pre-commit.ci](https://pre-commit.ci).

This would...

1. Lint markdown before commits are made.
2. Automatically fix issues in markdown before commits/pull requests are made.
3. Check Pull Requests to documentation files (`*.md` and `doc/**/*.md`) are correctly linted if contributors haven't used `pre-commit` hooks locally.

## `.pre-commit-config.yaml`...

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

 - repo: https://github.com/DavidAnson/markdownlint-cli2
   rev: v0.13.0
   hooks:
     - id: markdownlint-cli2
       args: []

ci:
 autofix_prs: true
 autofix_commit_msg: '[pre-commit.ci] Fixing issues with pre-commit'
 autoupdate_schedule: weekly
 autoupdate_commit_msg: '[pre-commit.ci] pre-commit-autoupdate'
 skip: [] # Optionally list ids of hooks to skip on CI
```

## `.markdownlint-cli2.yaml`

A basic configuration file is below, a full list of customisable linting rules can be found [here](https://github.com/DavidAnson/markdownlint/blob/v0.32.1/README.md#rules--aliases)

```yaml
config:

# MD013 - line-length
  line_length:
    line_length: 80
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div

globs:

- "docs/**/*.md"
- "*.md"

fix: true
```
